@startuml
skinparam DefaultFontSize 48
skinparam dpi 240

start
:Initialize float accumulator;
repeat
    :Initialize int32 accumulator;
    repeat
        :Load int8 input values;
        :int8 matrix multiplication;
    repeat while (More values in block?) is (Yes)
    ->No;
    #FF7777:Write back int32 results;
    :Scale int accumulator with block scales;
    :Increment float accumulator with scaled int;
repeat while (More input blocks?) is (Yes)
stop
@enduml
